import Foundation

extension String {

    struct Server {

        struct Gender {
            static var None: String { return "NONE" }
            static var Male: String { return "MALE" }
            static var Female: String { return "FEMALE" }
        }

        struct Country {
            static var None: String { return "NONE" }
            static var Afghanistan: String { return "AFGHANISTAN" }
            static var Albania: String { return "ALBANIA" }
            static var Algeria: String { return "ALGERIA" }
            static var Andorra: String { return "ANDORRA" }
            static var Angola: String { return "ANGOLA" }
            static var AntiguaAndBarbuda: String { return "ANTIGUAANDBARBUDA" }
            static var Argentina: String { return "ARGENTINA" }
            static var Armenia: String { return "ARMENIA" }
            static var Aruba: String { return "ARUBA" }
            static var Australia: String { return "AUSTRALIA" }
            static var Austria: String { return "AUSTRIA" }
            static var Azerbaijan: String { return "AZERBAIJAN" }
            static var Bahamas: String { return "BAHAMAS" }
            static var Bahrain: String { return "BAHRAIN" }
            static var Bangladesh: String { return "BANGLADESH" }
            static var Barbados: String { return "BARBADOS" }
            static var Belarus: String { return "BELARUS" }
            static var Belgium: String { return "BELGIUM" }
            static var Belize: String { return "BELIZE" }
            static var Benin: String { return "BENIN" }
            static var Bhutan: String { return "BHUTAN" }
            static var Bolivia: String { return "BOLIVIA" }
            static var BosniaAndHerzegovina: String { return "BOSNIAANDHERZEGOVINA" }
            static var Botswana: String { return "BOTSWANA" }
            static var Brazil: String { return "BRAZIL" }
            static var Brunei: String { return "BRUNEI" }
            static var Bulgaria: String { return "BULGARIA" }
            static var BurkinaFaso: String { return "BURKINAFASO" }
            static var Burma: String { return "BURMA" }
            static var Burundi: String { return "BURUNDI" }
            static var Cambodia: String { return "CAMBODIA" }
            static var Cameroon: String { return "CAMEROON" }
            static var Canada: String { return "CANADA" }
            static var CaboVerde: String { return "CABOVERDE" }
            static var CentralAfricanRepublic: String { return "CENTRALAFRICANREPUBLIC" }
            static var Chad: String { return "CHAD" }
            static var Chile: String { return "CHILE" }
            static var China: String { return "CHINA" }
            static var Colombia: String { return "COLOMBIA" }
            static var Comoros: String { return "COMOROS" }
            static var CostaRica: String { return "COSTARICA" }
            static var CotedIvoire: String { return "COTEDIVOIRE" }
            static var Croatia: String { return "CROATIA" }
            static var Cuba: String { return "CUBA" }
            static var Curacao: String { return "CURACAO" }
            static var Cyprus: String { return "CYPRUS" }
            static var Czechia: String { return "CZECHIA" }
            static var DemocraticRepublicOfTheCongo: String { return "DEMOCRATICREPUBLICOFTHECONGO" }
            static var Denmark: String { return "DENMARK" }
            static var Djibouti: String { return "DJIBOUTI" }
            static var Dominica: String { return "DOMINICA" }
            static var DominicanRepublic: String { return "DOMINICANREPUBLIC" }
            static var Ecuador: String { return "ECUADOR" }
            static var Egypt: String { return "EGYPT" }
            static var ElSalvador: String { return "ELSALVADOR" }
            static var EquatorialGuinea: String { return "EQUATORIALGUINEA" }
            static var Eritrea: String { return "ERITREA" }
            static var Estonia: String { return "ESTONIA" }
            static var Ethiopia: String { return "ETHIOPIA" }
            static var Fiji: String { return "FIJI" }
            static var Finland: String { return "FINLAND" }
            static var France: String { return "FRANCE" }
            static var Gabon: String { return "GABON" }
            static var Gambia: String { return "GAMBIA" }
            static var Georgia: String { return "GEORGIA" }
            static var Germany: String { return "GERMANY" }
            static var Ghana: String { return "GHANA" }
            static var Greece: String { return "GREECE" }
            static var Grenada: String { return "GRENADA" }
            static var Guatemala: String { return "GUATEMALA" }
            static var Guinea: String { return "GUINEA" }
            static var GuineaBissau: String { return "GUINEABISSAU" }
            static var Guyana: String { return "GUYANA" }
            static var Haiti: String { return "HAITI" }
            static var HolySee: String { return "HOLYSEE" }
            static var Honduras: String { return "HONDURAS" }
            static var HongKong: String { return "HONGKONG" }
            static var Hungary: String { return "HUNGARY" }
            static var Iceland: String { return "ICELAND" }
            static var India: String { return "INDIA" }
            static var Indonesia: String { return "INDONESIA" }
            static var Iran: String { return "IRAN" }
            static var Iraq: String { return "IRAQ" }
            static var Ireland: String { return "IRELAND" }
            static var Israel: String { return "ISRAEL" }
            static var Italy: String { return "ITALY" }
            static var Jamaica: String { return "JAMAICA" }
            static var Japan: String { return "JAPAN" }
            static var Jordan: String { return "JORDAN" }
            static var Kazakhstan: String { return "KAZAKHSTAN" }
            static var Kenya: String { return "KENYA" }
            static var Kiribati: String { return "KIRIBATI" }
            static var Kosovo: String { return "KOSOVO" }
            static var Kuwait: String { return "KUWAIT" }
            static var Kyrgyzstan: String { return "KYRGYZSTAN" }
            static var Laos: String { return "LAOS" }
            static var Latvia: String { return "LATVIA" }
            static var Lebanon: String { return "LEBANON" }
            static var Lesotho: String { return "LESOTHO" }
            static var Liberia: String { return "LIBERIA" }
            static var Libya: String { return "LIBYA" }
            static var Liechtenstein: String { return "LIECHTENSTEIN" }
            static var Lithuania: String { return "LITHUANIA" }
            static var Luxembourg: String { return "LUXEMBOURG" }
            static var Macau: String { return "MACAU" }
            static var Macedonia: String { return "MACEDONIA" }
            static var Madagascar: String { return "MADAGASCAR" }
            static var Malawi: String { return "MALAWI" }
            static var Malaysia: String { return "MALAYSIA" }
            static var Maldives: String { return "MALDIVES" }
            static var Mali: String { return "MALI" }
            static var Malta: String { return "MALTA" }
            static var MarshallIslands: String { return "MARSHALLISLANDS" }
            static var Mauritania: String { return "MAURITANIA" }
            static var Mauritius: String { return "MAURITIUS" }
            static var Mexico: String { return "MEXICO" }
            static var Micronesia: String { return "MICRONESIA" }
            static var Moldova: String { return "MOLDOVA" }
            static var Monaco: String { return "MONACO" }
            static var Mongolia: String { return "MONGOLIA" }
            static var Montenegro: String { return "MONTENEGRO" }
            static var Morocco: String { return "MOROCCO" }
            static var Mozambique: String { return "MOZAMBIQUE" }
            static var Namibia: String { return "NAMIBIA" }
            static var Nauru: String { return "NAURU" }
            static var Nepal: String { return "NEPAL" }
            static var Netherlands: String { return "NETHERLANDS" }
            static var NewZealand: String { return "NEWZEALAND" }
            static var Nicaragua: String { return "NICARAGUA" }
            static var Niger: String { return "NIGER" }
            static var Nigeria: String { return "NIGERIA" }
            static var NorthKorea: String { return "NORTHKOREA" }
            static var Norway: String { return "NORWAY" }
            static var Oman: String { return "OMAN" }
            static var Pakistan: String { return "PAKISTAN" }
            static var Palau: String { return "PALAU" }
            static var PalestinianTerritories: String { return "PALESTINIANTERRITORIES" }
            static var Panama: String { return "PANAMA" }
            static var PapuaNewGuinea: String { return "PAPUANEWGUINEA" }
            static var Paraguay: String { return "PARAGUAY" }
            static var Peru: String { return "PERU" }
            static var Philippines: String { return "PHILIPPINES" }
            static var Poland: String { return "POLAND" }
            static var Portugal: String { return "PORTUGAL" }
            static var Qatar: String { return "QATAR" }
            static var RepublicOfTheCongo: String { return "REPUBLICOFTHECONGO" }
            static var Romania: String { return "ROMANIA" }
            static var Russia: String { return "RUSSIA" }
            static var Rwanda: String { return "RWANDA" }
            static var SaintKittsAndNevis: String { return "SAINTKITTSANDNEVIS" }
            static var SaintLucia: String { return "SAINTLUCIA" }
            static var SaintVincentAndTheGrenadines: String { return "SAINTVINCENTANDTHEGRENADINES" }
            static var Samoa: String { return "SAMOA" }
            static var SanMarino: String { return "SANMARINO" }
            static var SaoTomeAndPrincipe: String { return "SAOTOMEANDPRINCIPE" }
            static var SaudiArabia: String { return "SAUDIARABIA" }
            static var Senegal: String { return "SENEGAL" }
            static var Serbia: String { return "SERBIA" }
            static var Seychelles: String { return "SEYCHELLES" }
            static var SierraLeone: String { return "SIERRALEONE" }
            static var Singapore: String { return "SINGAPORE" }
            static var SintMaarten: String { return "SINTMAARTEN" }
            static var Slovakia: String { return "SLOVAKIA" }
            static var Slovenia: String { return "SLOVENIA" }
            static var SolomonIslands: String { return "SOLOMONISLANDS" }
            static var Somalia: String { return "SOMALIA" }
            static var SouthAfrica: String { return "SOUTHAFRICA" }
            static var SouthKorea: String { return "SOUTHKOREA" }
            static var SouthSudan: String { return "SOUTHSUDAN" }
            static var Spain: String { return "SPAIN" }
            static var SriLanka: String { return "SRILANKA" }
            static var Sudan: String { return "SUDAN" }
            static var Suriname: String { return "SURINAME" }
            static var Swaziland: String { return "SWAZILAND" }
            static var Sweden: String { return "SWEDEN" }
            static var Switzerland: String { return "SWITZERLAND" }
            static var Syria: String { return "SYRIA" }
            static var Taiwan: String { return "TAIWAN" }
            static var Tajikistan: String { return "TAJIKISTAN" }
            static var Tanzania: String { return "TANZANIA" }
            static var Thailand: String { return "THAILAND" }
            static var TimorLeste: String { return "TIMORLESTE" }
            static var Togo: String { return "TOGO" }
            static var Tonga: String { return "TONGA" }
            static var TrinidadAndTobago: String { return "TRINIDADANDTOBAGO" }
            static var Tunisia: String { return "TUNISIA" }
            static var Turkey: String { return "TURKEY" }
            static var Turkmenistan: String { return "TURKMENISTAN" }
            static var Tuvalu: String { return "TUVALU" }
            static var Uganda: String { return "UGANDA" }
            static var Ukraine: String { return "UKRAINE" }
            static var UnitedArabEmirates: String { return "UNITEDARABEMIRATES" }
            static var UnitedKingdom: String { return "UNITEDKINGDOM" }
            static var UnitedStatesOfAmerica: String { return "UNITEDSTATESOFAMERICA" }
            static var Uruguay: String { return "URUGUAY" }
            static var Uzbekistan: String { return "UZBEKISTAN" }
            static var Vanuatu: String { return "VANUATU" }
            static var Venezuela: String { return "VIETNAM" }
            static var Vietnam: String { return "VIETNAM" }
            static var Yemen: String { return "YEMEN" }
            static var Zambia: String { return "ZAMBIA" }
            static var Zimbabwe: String { return "ZIMBABWE" }
        }

        struct LanguageName {
            static var None: String { return "NONE" }
            static var Afrikaans: String { return "AFRIKAANS" }
            static var Albanian: String { return "ALBANIAN" }
            static var Amharic: String { return "AMHARIC" }
            static var Arabic: String { return "ARABIC" }
            static var Aramaic: String { return "ARAMAIC" }
            static var Armenian: String { return "ARMENIAN" }
            static var Assamese: String { return "ASSAMESE" }
            static var Aymara: String { return "AYMARA" }
            static var Azerbaijani: String { return "AZERBAIJANI" }
            static var Balochi: String { return "BALOCHI" }
            static var Bamanankan: String { return "BAMANANKAN" }
            static var Bashkir: String { return "BASHKIR" }
            static var Basque: String { return "BASQUE" }
            static var Belarusian: String { return "BELARUSIAN" }
            static var Bengali: String { return "BENGALI" }
            static var Bhojpuri: String { return "BHOJPURI" }
            static var Bislama: String { return "BISLAMA" }
            static var Bosnian: String { return "BOSNIAN" }
            static var Brahui: String { return "BRAHUI" }
            static var Bulgarian: String { return "BULGARIAN" }
            static var Burmese: String { return "BURMESE" }
            static var Cantonese: String { return "CANTONESE" }
            static var Catalan: String { return "CATALAN" }
            static var Cebuano: String { return "CEBUANO" }
            static var Chechen: String { return "CHECHEN" }
            static var Cherokee: String { return "CHEROKEE" }
            static var Croatian: String { return "CROATIAN" }
            static var Czech: String { return "CZECH" }
            static var Dakota: String { return "DAKOTA" }
            static var Danish: String { return "DANISH" }
            static var Dari: String { return "DARI" }
            static var Dholuo: String { return "DHOLUO" }
            static var Dutch: String { return "DUTCH" }
            static var English: String { return "ENGLISH" }
            static var Esperanto: String { return "ESPERANTO" }
            static var Estonian: String { return "ESTONIAN" }
            static var Ewe: String { return "EWE" }
            static var Finnish: String { return "FINNISH" }
            static var French: String { return "FRENCH" }
            static var Georgian: String { return "GEORGIAN" }
            static var German: String { return "GERMAN" }
            static var Gikuyu: String { return "GIKUYU" }
            static var Greek: String { return "GREEK" }
            static var Guarani: String { return "GUARANI" }
            static var Gujarati: String { return "GUJARATI" }
            static var HaitianCreole: String { return "HAITIANCREOLE" }
            static var Hausa: String { return "HAUSA" }
            static var Hawaiian: String { return "HAWAIIAN" }
            static var Hebrew: String { return "HEBREW" }
            static var Hiligaynon: String { return "HILIGAYNON" }
            static var Hindi: String { return "HINDI" }
            static var Hungarian: String { return "HUNGARIAN" }
            static var Icelandic: String { return "ICELANDIC" }
            static var Igbo: String { return "IGBO" }
            static var Ilocano: String { return "ILOCANO" }
            static var Indonesian: String { return "INDONESIAN" }
            static var Inuit: String { return "INUIT" }
            static var IrishGaelic: String { return "IRISHGAELIC" }
            static var Italian: String { return "ITALIAN" }
            static var Japanese: String { return "JAPANESE" }
            static var Jarai: String { return "JARAI" }
            static var Javanese: String { return "JAVANESE" }
            static var Kiche: String { return "KICHE" }
            static var Kabyle: String { return "KABYLE" }
            static var Kannada: String { return "KANNADA" }
            static var Kashmiri: String { return "KASHMIRI" }
            static var Kazakh: String { return "KAZAKH" }
            static var Khmer: String { return "KHMER" }
            static var Khoekhoe: String { return "KHOEKHOE" }
            static var Korean: String { return "KOREAN" }
            static var Kurdish: String { return "KURDISH" }
            static var Kyrgyz: String { return "KYRGYZ" }
            static var Lao: String { return "LAO" }
            static var Latin: String { return "LATIN" }
            static var Latvian: String { return "LATVIAN" }
            static var Lingala: String { return "LINGALA" }
            static var Lithuanian: String { return "LITHUANIAN" }
            static var Macedonian: String { return "MACEDONIAN" }
            static var Maithili: String { return "MAITHILI" }
            static var Malagasy: String { return "MALAGASY" }
            static var Malay: String { return "MALAY" }
            static var Malayalam: String { return "MALAYALAM" }
            static var Mandarin: String { return "MANDARIN" }
            static var Marathi: String { return "MARATHI" }
            static var Mende: String { return "MENDE" }
            static var Mongolian: String { return "MONGOLIAN" }
            static var Nahuatl: String { return "NAHUATL" }
            static var Navajo: String { return "NAVAJO" }
            static var Nepali: String { return "NEPALI" }
            static var Norwegian: String { return "NORWEGIAN" }
            static var Ojibwa: String { return "OJIBWA" }
            static var Oriya: String { return "ORIYA" }
            static var Oromo: String { return "OROMO" }
            static var Pashto: String { return "PASHTO" }
            static var Persian: String { return "PERSIAN" }
            static var Polish: String { return "POLISH" }
            static var Portuguese: String { return "PORTUGUESE" }
            static var Punjabi: String { return "PUNJABI" }
            static var Quechua: String { return "QUECHUA" }
            static var Romani: String { return "ROMANI" }
            static var Romanian: String { return "ROMANIAN" }
            static var Russian: String { return "RUSSIAN" }
            static var Rwanda: String { return "RWANDA" }
            static var Samoan: String { return "SAMOAN" }
            static var Sanskrit: String { return "SANSKRIT" }
            static var Serbian: String { return "SERBIAN" }
            static var Shona: String { return "SHONA" }
            static var Sindhi: String { return "SINDHI" }
            static var Sinhala: String { return "SINHALA" }
            static var Slovak: String { return "SLOVAK" }
            static var Slovene: String { return "SLOVENE" }
            static var Somali: String { return "SOMALI" }
            static var Spanish: String { return "SPANISH" }
            static var Swahili: String { return "SWAHILI" }
            static var Swedish: String { return "SWEDISH" }
            static var Tachelhit: String { return "TACHELHIT" }
            static var Tagalog: String { return "TAGALOG" }
            static var Tajiki: String { return "TAJIKI" }
            static var Tamil: String { return "TAMIL" }
            static var Tatar: String { return "TATAR" }
            static var Telugu: String { return "TELUGU" }
            static var Thai: String { return "THAI" }
            static var Tigrigna: String { return "TIGRIGNA" }
            static var TokPisin: String { return "TOKPISIN" }
            static var Turkish: String { return "TURKISH" }
            static var Turkmen: String { return "TURKMEN" }
            static var Ukrainian: String { return "UKRAINIAN" }
            static var Urdu: String { return "URDU" }
            static var Uyghur: String { return "UYGHUR" }
            static var Uzbek: String { return "UZBEK" }
            static var Vietnamese: String { return "VIETNAMESE" }
            static var Warlpiri: String { return "WARLPIRI" }
            static var Welsh: String { return "WELSH" }
            static var Wolof: String { return "WOLOF" }
            static var Xhosa: String { return "XHOSA" }
            static var Yakut: String { return "YAKUT" }
            static var Yiddish: String { return "YIDDISH" }
            static var Yoruba: String { return "YORUBA" }
            static var Yucatec: String { return "YUCATEC" }
            static var Zapotec: String { return "ZAPOTEC" }
            static var Zulu: String { return "ZULU" }
        }

        struct LanguageLevel {
            static var None: String { return "NONE" }
            static var Beginner: String { return "BEGINNER" }
            static var Intermediate: String { return "INTERMEDIATE" }
            static var Advanced: String { return "ADVANCED" }
            static var Fluent: String { return "FLUENT" }
            static var Native: String { return "NATIVE" }

        }
        
    }

}
